name: Build for OSX
on: 
    push:
    pull_request:
    release:
      types: # This configuration does not affect the page_build event above
        - created

jobs:
    build:
        #if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
        runs-on: macos-latest
        steps:           
            - uses: actions/checkout@v1
              with:
                  submodules: true
                    
            - name: Install Triton dependecies
              run: |
                 brew install boost
                 echo "set(VCPKG_BUILD_TYPE release)" >> $VCPKG_INSTALLATION_ROOT/triplets/x64-osx.cmake
                 vcpkg install capstone[x86,arm,arm64] z3    
                  
            - name: Download and build Triton x64
              run: |
                  cd ..
                  git clone --depth 1 --branch v0.9 https://github.com/JonathanSalwan/Triton
                  cd Triton
                  cmake -S . -B build_x64 -DCMAKE_INSTALL_PREFIX=install_dir -DPYTHON_BINDINGS=OFF -DSTATICLIB=ON -DZ3_INCLUDE_DIRS="$VCPKG_INSTALLATION_ROOT/installed/x64-osx/include" -DCAPSTONE_INCLUDE_DIRS="$VCPKG_INSTALLATION_ROOT/installed/x64-osx/include"
                  cmake --build build_x64 --target install --config Release --parallel 2
                      
            - name: Dowload IDA SDKs
              shell: bash
              env:
                IDA_SDK: ${{ secrets. DOWNLOAD_LINK_IDA_SDK }}
              run: |
                  cd ..
                  curl -L -o IDA_SDKs.zip "$IDA_SDK"
                  unzip IDA_SDKs.zip -d IDA_SDKs              
            
            - name: Build Ponce IDA 7.0
              run: |
                  unzip ../IDA_SDKs/idasdk70.zip -d ../IDA_SDKs
                  cmake -S . -B build_x64_7.0 -DIDASDK_ROOT_DIR="../IDA_SDKs/idasdk70" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DTRITON_INCLUDE_DIR="../Triton/install_dir/include" -DTRITON_LIBRARY="../Triton/install_dir/lib/libtriton.a" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                  cmake --build build_x64_7.0 --config Release --parallel 2
                  
            - name: Build Ponce IDA 7.1
              run: |
                  unzip ../IDA_SDKs/idasdk71.zip -d ../IDA_SDKs
                  cmake -S . -B build_x64_7.1 -DIDASDK_ROOT_DIR="../IDA_SDKs/idasdk71" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DTRITON_INCLUDE_DIR="../Triton/install_dir/include" -DTRITON_LIBRARY="../Triton/install_dir/lib/libtriton.a" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                  cmake --build build_x64_7.1 --config Release --parallel 2
            
            - name: Build Ponce IDA 7.2
              run: |
                  unzip ../IDA_SDKs/idasdk72.zip -d ../IDA_SDKs
                  cmake -S . -B build_x64_7.2 -DIDASDK_ROOT_DIR="../IDA_SDKs/idasdk72" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DTRITON_INCLUDE_DIR="../Triton/install_dir/include" -DTRITON_LIBRARY="../Triton/install_dir/lib/libtriton.a" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                  cmake --build build_x64_7.2 --config Release --parallel 2
            
            - name: Build Ponce IDA 7.3
              run: |
                  unzip ../IDA_SDKs/idasdk73.zip -d ../IDA_SDKs
                  cmake -S . -B build_x64_7.3 -DUSE_CLANG=ON -DIDASDK_ROOT_DIR="../IDA_SDKs/idasdk73" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DTRITON_INCLUDE_DIR="../Triton/install_dir/include" -DTRITON_LIBRARY="../Triton/install_dir/lib/libtriton.a" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                  cmake --build build_x64_7.3 --config Release --parallel 2
            
            - name: Build Ponce IDA 7.4
              run: |
                  unzip ../IDA_SDKs/idasdk74.zip -d ../IDA_SDKs
                  cmake -S . -B build_x64_7.4 -DUSE_CLANG=ON -DIDASDK_ROOT_DIR="../IDA_SDKs/idasdk74" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DTRITON_INCLUDE_DIR="../Triton/install_dir/include" -DTRITON_LIBRARY="../Triton/install_dir/lib/libtriton.a" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                  cmake --build build_x64_7.4 --config Release --parallel 2
                      
            - name: Build Ponce IDA 7.5
              run: |
                  unzip ../IDA_SDKs/idasdk75.zip -d ../IDA_SDKs
                  cmake -S . -B build_x64_7.5 -DUSE_CLANG=ON -DIDASDK_ROOT_DIR="../IDA_SDKs/idasdk75" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DTRITON_INCLUDE_DIR="../Triton/install_dir/include" -DTRITON_LIBRARY="../Triton/install_dir/lib/libtriton.a" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                  cmake --build build_x64_7.5 --config Release --parallel 2

            - name: Build Ponce IDA 7.6
              run: |
                  unzip ../IDA_SDKs/idasdk76.zip -d ../IDA_SDKs
                  cmake -S . -B build_x64_7.6 -DUSE_CLANG=ON -DIDASDK_ROOT_DIR="../IDA_SDKs/idasdk76" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DTRITON_INCLUDE_DIR="../Triton/install_dir/include" -DTRITON_LIBRARY="../Triton/install_dir/lib/libtriton.a" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                  cmake --build build_x64_7.6 --config Release --parallel 2

            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida70
                  path: build_x64_7.0/Ponce64.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida70
                  path: build_x64_7.0/Ponce.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida71
                  path: build_x64_7.1/Ponce64.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida71
                  path: build_x64_7.1/Ponce.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida72
                  path: build_x64_7.2/Ponce64.dylib
            
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida72
                  path: build_x64_7.2/Ponce.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida73
                  path: build_x64_7.3/Ponce64.dylib

            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida73
                  path: build_x64_7.3/Ponce.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida74
                  path: build_x64_7.4/Ponce64.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida74
                  path: build_x64_7.4/Ponce.dylib
            
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida75
                  path: build_x64_7.5/Ponce64.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida75
                  path: build_x64_7.5/Ponce.dylib

            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida76
                  path: build_x64_7.6/Ponce64.dylib
                  
            - uses: actions/upload-artifact@master
              with:
                  name: Ponce_ida76
                  path: build_x64_7.6/Ponce.dylib      
                  
    release:
        runs-on: ubuntu-latest
        if: github.event_name == 'release'
        needs: build
        steps:
            - name: Download all OSX arifacts
              uses: actions/download-artifact@v2
              with:
                  path: ./my_artifacts
            
            - name: Set output
              id: vars
              run: |
                echo ::set-output name=tag::${GITHUB_REF#refs/*/}
                
            - name: Build zip file
              env:
                RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
              run: |             
                cd my_artifacts
                zip -r ../ponce-$RELEASE_VERSION-osx.zip *

            
            - name: Upload OSX artifacts
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./ponce-${{ steps.vars.outputs.tag }}-osx.zip
                  asset_name: ponce-${{ steps.vars.outputs.tag }}-osx.zip
                  asset_content_type: application/zip

                  